language: go

go:
  - tip

services:
  - docker

sudo: false

install:
  - go get github.com/constabulary/gb/...
  - make build-linux
  - make docker-image
  - make docker-run-daemon

script:
  - docker ps | grep -q go_web_server
  - make test
