language: go

go:
  - 1.6

services:
  - docker

sudo: false

install:
  # not using gb atm as it does not have support for static linking
  #- go get github.com/constabulary/gb/...
  - make build-linux
  - make docker-image
  - make docker-run-daemon

script:
  - docker ps | grep -q go_web_server
  - make test
