language: go

go:
  - 1.6

services:
  - docker
  - postgresql

addons:
  postgresql: "9.4"

sudo: required

before_script:
  - ifconfig

install:
  - psql -c 'create database docker_test_developement;' -U postgres
  - psql -c "select * from pg_settings where name like '%address%'"
  - go get -u github.com/jteeuwen/go-bindata/...

  # not using gb atm as it does not have support for static linking
  #- go get github.com/constabulary/gb/...
  - make build-linux
  - make docker-image
  - make docker-run-daemon
  - docker logs testing_container

script:
  - docker ps -a
  - docker ps | grep -q testing_container
  - make test1
  - make test
