language: go

go:
  - 1.6

services:
  - docker
  - postgresql

sudo: false

before_script:

install:
  - psql -c 'create database docker_test;' -U postgres
  - go get -u github.com/jteeuwen/go-bindata/...

  # not using gb atm as it does not have support for static linking
  #- go get github.com/constabulary/gb/...
  - make build-linux
  - make docker-image
  - make docker-run-daemon

script:
  - docker ps
  - docker ps | grep -q go_web_server
  - make test
